package com.mininglamp.uums.db.model;

public class ProductDictDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_dict.product_id
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_dict.product_name
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_dict.description
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_dict.product_id
     *
     * @return the value of product_dict.product_id
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_dict.product_id
     *
     * @param productId the value for product_dict.product_id
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_dict.product_name
     *
     * @return the value of product_dict.product_name
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_dict.product_name
     *
     * @param productName the value for product_dict.product_name
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_dict.description
     *
     * @return the value of product_dict.description
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_dict.description
     *
     * @param description the value for product_dict.description
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}