package com.mininglamp.uums.db.dao;

import com.mininglamp.uums.db.model.ProductDictDO;

import java.util.List;

public interface ProductDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_dict
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_dict
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int insert(ProductDictDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_dict
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int insertSelective(ProductDictDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_dict
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    ProductDictDO selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_dict
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int updateByPrimaryKeySelective(ProductDictDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_dict
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int updateByPrimaryKey(ProductDictDO record);

    List<ProductDictDO> getAllProductDict();
}