package com.mininglamp.uums.db.dao;

import com.mininglamp.uums.db.model.TenantResourceRelationDO;

import java.util.List;

public interface TenantResourceRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_resource_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int deleteByPrimaryKey(Integer tenantResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_resource_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int insert(TenantResourceRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_resource_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int insertSelective(TenantResourceRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_resource_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    TenantResourceRelationDO selectByPrimaryKey(Integer tenantResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_resource_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int updateByPrimaryKeySelective(TenantResourceRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_resource_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int updateByPrimaryKey(TenantResourceRelationDO record);

    List<TenantResourceRelationDO> getByTenantId(Integer tenantId);
}