package com.mininglamp.uums.db.dao;

import com.mininglamp.uums.db.model.TenantProductRelationDO;

import java.util.List;

public interface TenantProductRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_product_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int deleteByPrimaryKey(Integer tenantProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_product_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int insert(TenantProductRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_product_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int insertSelective(TenantProductRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_product_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    TenantProductRelationDO selectByPrimaryKey(Integer tenantProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_product_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int updateByPrimaryKeySelective(TenantProductRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant_product_relation
     *
     * @mbg.generated Wed Nov 11 10:48:14 CST 2020
     */
    int updateByPrimaryKey(TenantProductRelationDO record);

    List<TenantProductRelationDO> getByTenantId(Integer tenantId);
}